# Generated by Django 3.1.6 on 2021-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
