# Generated by Django 3.1.6 on 2021-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdetail', '0002_auto_20210220_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
